# Generated by Django 3.0.7 on 2020-06-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='id',
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Subservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subservice_name', models.CharField(max_length=100)),
                ('subservice_description', models.CharField(max_length=500)),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Services')),
            ],
        ),
    ]
